// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
	export interface GlobalComponents {
		404: typeof import("./src/components/special/404.vue")["default"];
		AConfigProvider: typeof import("ant-design-vue/es")["ConfigProvider"];
		AMenu: typeof import("ant-design-vue/es")["Menu"];
		AMenuItem: typeof import("ant-design-vue/es")["MenuItem"];
		ASubMenu: typeof import("ant-design-vue/es")["SubMenu"];
		Content: typeof import("./src/components/layout/header/components/content.vue")["default"];
		Header: typeof import("./src/components/layout/header/index.vue")["default"];
		Logo: typeof import("./src/components/layout/header/components/logo.vue")["default"];
		Menu: typeof import("./src/components/layout/menu/index.vue")["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SubMenu: typeof import("./src/components/layout/menu/sub-menu.vue")["default"];
		Table: typeof import("./src/components/table/index.vue")["default"];
		User: typeof import("./src/components/layout/header/components/user.vue")["default"];
	}
}
